# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NaviGUI.ui'
#
# Created: Thu Oct 19 19:49:00 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(607, 468)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("color: rgb(85, 0, 0);\n"
"background-color:rgb(255, 247, 225)")
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vonLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.vonLabel.setFont(font)
        self.vonLabel.setObjectName("vonLabel")
        self.verticalLayout_2.addWidget(self.vonLabel)
        self.bisLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bisLabel.setFont(font)
        self.bisLabel.setObjectName("bisLabel")
        self.verticalLayout_2.addWidget(self.bisLabel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vonInput = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.vonInput.setFont(font)
        self.vonInput.setStyleSheet("background-color:rgb(255, 255, 255)rgb(255, 255, 255)")
        self.vonInput.setObjectName("vonInput")
        self.verticalLayout_3.addWidget(self.vonInput)
        self.bisInput = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bisInput.setFont(font)
        self.bisInput.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.bisInput.setObjectName("bisInput")
        self.verticalLayout_3.addWidget(self.bisInput)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.outputNavi = QtGui.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputNavi.setFont(font)
        self.outputNavi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputNavi.setStyleSheet("background-color:rgb(255,255,255)")
        self.outputNavi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.outputNavi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.outputNavi.setObjectName("outputNavi")
        self.verticalLayout.addWidget(self.outputNavi)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jsonLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.jsonLabel.setFont(font)
        self.jsonLabel.setStyleSheet("background-color:rgb(255, 247, 225)")
        self.jsonLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jsonLabel.setObjectName("jsonLabel")
        self.horizontalLayout_3.addWidget(self.jsonLabel)
        self.dialChoose = QtGui.QDial(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dialChoose.setFont(font)
        self.dialChoose.setStyleSheet("background-color:rgb(144, 144, 144);\n"
"color: rgb(255, 247, 225)")
        self.dialChoose.setObjectName("dialChoose")
        self.horizontalLayout_3.addWidget(self.dialChoose)
        self.xmlLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.xmlLabel.setFont(font)
        self.xmlLabel.setStyleSheet("background-color:rgb(255, 247, 225)")
        self.xmlLabel.setObjectName("xmlLabel")
        self.horizontalLayout_3.addWidget(self.xmlLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.submitButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"color: rgb(255,255,255)")
        self.submitButton.setAutoDefault(True)
        self.submitButton.setDefault(False)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_2.addWidget(self.submitButton)
        self.resetButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"color: rgb(255,255,255)")
        self.resetButton.setAutoDefault(True)
        self.resetButton.setDefault(False)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.closeButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"color: rgb(255,255,255)")
        self.closeButton.setAutoDefault(True)
        self.closeButton.setDefault(False)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("background-color:rgb(255, 247, 225)")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_4.addWidget(self.statusLabel)
        self.usability = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.usability.setFont(font)
        self.usability.setStyleSheet("background-color:rgb(255, 247, 225)")
        self.usability.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usability.setObjectName("usability")
        self.horizontalLayout_4.addWidget(self.usability)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.vonInput.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.bisInput.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.outputNavi.clear)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.vonInput, self.bisInput)
        Form.setTabOrder(self.bisInput, self.submitButton)
        Form.setTabOrder(self.submitButton, self.resetButton)
        Form.setTabOrder(self.resetButton, self.closeButton)
        Form.setTabOrder(self.closeButton, self.outputNavi)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "REST-ful Client | TEKIN", None, QtGui.QApplication.UnicodeUTF8))
        self.vonLabel.setText(QtGui.QApplication.translate("Form", "VON:", None, QtGui.QApplication.UnicodeUTF8))
        self.bisLabel.setText(QtGui.QApplication.translate("Form", "BIS:", None, QtGui.QApplication.UnicodeUTF8))
        self.jsonLabel.setText(QtGui.QApplication.translate("Form", "JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlLabel.setText(QtGui.QApplication.translate("Form", "XML", None, QtGui.QApplication.UnicodeUTF8))
        self.submitButton.setText(QtGui.QApplication.translate("Form", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("Form", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.usability.setText(QtGui.QApplication.translate("Form", "#Usability", None, QtGui.QApplication.UnicodeUTF8))

